# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to=users.models.profile_picture_document_destination, verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'permissions': (('is_general_director', 'Es director general'), ('is_project_director', 'Es director de obras'), ('is_vicepresident', 'Es vicepresidente empresarial'), ('is_head_manager', 'Es jefe de administraci\xf3n'), ('is_president', 'Es presidente')),
            },
        ),
    ]
