# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpuser',
            options={'permissions': (('is_general_director', 'Es director general'), ('is_project_director', 'Es director de obras'), ('is_vicepresident', 'Es vicepresidente empresarial'), ('is_head_manager', 'Es jefe de administraci\xf3n'), ('is_president', 'Es presidente'), ('is_rhadmin', 'Es administrador RH')), 'verbose_name_plural': 'Usuarios'},
        ),
    ]
