# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Archivado'), ('C', 'Actual')], default='A', max_length=1)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Precio Unitario')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='ConceptMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='Clave')),
                ('description', models.TextField(max_length=4096, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estimaciones',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Descripci\xf3n')),
                ('parent_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida Padre')),
            ],
            options={
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('mime', models.CharField(max_length=128, verbose_name='MIME')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, verbose_name='Clave de la Estimaci\xf3n')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Progreso')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Estimate', verbose_name='Estimaci\xf3n')),
            ],
            options={
                'verbose_name_plural': 'Avances',
            },
        ),
        migrations.CreateModel(
            name='ProgressEstimateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512, verbose_name='Descripci\xf3n')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('progress_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ProgressEstimate', verbose_name='Estimaci\xf3n')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ERPUser', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave del Proyecto')),
                ('name', models.TextField(max_length=1024, verbose_name='Nombre del Proyecto')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Unidad')),
                ('abbreviation', models.CharField(max_length=16, unique=True, verbose_name='Abreviaci\xf3n')),
                ('quantification', models.CharField(choices=[('C', 'Continuous'), ('D', 'Discrete')], default='C', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='progressestimate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Unit', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='progress_estimate_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ProgressEstimateLog', verbose_name='Log de Estimaci\xf3n'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='conceptmaster',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida'),
        ),
        migrations.AddField(
            model_name='conceptmaster',
            name='parent_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.ConceptMaster', verbose_name='Concepto Padre'),
        ),
        migrations.AddField(
            model_name='conceptdetail',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ConceptMaster', verbose_name='master'),
        ),
        migrations.AddField(
            model_name='conceptdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Unit', verbose_name='Unidad'),
        ),
    ]
