# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-08 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='line_item_Est',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_item_Est', to='ERP.LineItem', verbose_name='Partida'),
            preserve_default=False,
        ),
    ]
