# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconcepts',
            name='OfThisEstimate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='De Esta Estimaci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractconcepts',
            name='ThisEstimate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='A Esta Estimaci\xf3n'),
            preserve_default=False,
        ),
    ]
