# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-29 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20190115_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractconcepts',
            options={'verbose_name_plural': 'ContractConcepts'},
        ),
        migrations.AddField(
            model_name='progressestimate',
            name='paid_out',
            field=models.FloatField(default=0.0, verbose_name='Total Pagado'),
        ),
    ]
