# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20190306_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribucionpagodetail',
            options={'verbose_name': 'Detalle de Distribuci\xf3n de Pago', 'verbose_name_plural': 'Detalle Distribuci\xf3n de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='tipopago',
            options={'verbose_name': 'Tipo de Pago', 'verbose_name_plural': 'Tipos de Pago'},
        ),
        migrations.AddField(
            model_name='documentacioncontrato',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, verbose_name='Descripci\xf3n del Archivo '),
        ),
        migrations.AlterField(
            model_name='documentacioncontrato',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre del Archivo '),
        ),
    ]
