# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_remove_contact_is_legal_representantive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_legal_representantive',
            field=models.BooleanField(default=False, verbose_name='Representante Legal'),
        ),
    ]
