# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-08 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_estimate_line_item_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressestimate',
            name='Real_Paid',
            field=models.FloatField(default=0.0, verbose_name='Cantidaid Real de Pago'),
        ),
    ]
