# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-19 17:36
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20190219_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='Total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, max_length=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Total Pagado'),
        ),
    ]
