# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_remove_bank_sat_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='sat_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.SATBank', verbose_name='Banco del SAT'),
        ),
    ]
