# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-29 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20190129_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressestimate',
            name='paid_out',
        ),
    ]
