# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-30 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0003_contact_is_legal_representantive'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administration_head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Administraci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='business_president',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Presidente Empresarial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='business_vice_president',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vicepresidente Empresarial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='construction_director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Director de Construcci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='general_director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Director General'),
            preserve_default=False,
        ),
    ]
