# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-06 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20190306_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacioncontrato',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descripci\xf3n del Archivo '),
        ),
    ]
