# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20171114_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='CLABE',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='CLABE Interbancaria'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 10, 37, 565435, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 10, 37, 565616, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 10, 37, 565235, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 22, 10, 37, 571964, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
