# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20190306_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionpagodetail',
            name='porcentaje',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Porcentaje'),
        ),
    ]
