# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_remove_progressestimate_paid_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='paid_out',
            field=models.FloatField(default=0.0, verbose_name='Pagado'),
        ),
    ]
