# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-19 18:24
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20190219_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_pactados', models.CharField(max_length=50, verbose_name='D\xedas Pactados')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ContratoContratista', verbose_name='Contrato')),
                ('line_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=50, verbose_name='Nombre del Archivo: ')),
                ('pdf_version', models.FileField(upload_to=ERP.models.upload_contract_file, verbose_name='Archivo PDF del contrato')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ContratoContratista', verbose_name='Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='PartidasContratoContratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_partida', models.CharField(blank=True, max_length=50, verbose_name='Monto de la Partida: ')),
                ('anticipo', models.CharField(blank=True, max_length=50, verbose_name='Anticipo: ')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino_propuesta', models.DateField(verbose_name='Fecha de Termino Propuesta')),
                ('fecha_termino_real', models.DateField(verbose_name='Fecha de Termino Real')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ContratoContratista', verbose_name='Contrato')),
                ('line_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida')),
            ],
        ),
    ]
