# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_bank_sat_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='sat_bank',
        ),
        migrations.DeleteModel(
            name='SATBank',
        ),
    ]
