# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-29 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_estimate_paid_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='paid_out',
        ),
    ]
