# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20180504_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoproject',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Obra'),
            preserve_default=False,
        ),
    ]
