# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20171114_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Nombre de la Persona'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 13, 10, 207691, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 13, 10, 207739, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 13, 10, 207634, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 22, 13, 10, 211869, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
