# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20171213_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='sat_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Bank', verbose_name='Banco del SAT'),
        ),
    ]
