# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 02:04
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20171106_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Deducciones Por Mala Calidad'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='deduction_comments',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 2, 4, 30, 205425, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 2, 4, 30, 205461, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 2, 4, 30, 205372, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 2, 4, 30, 209002, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
