# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20190307_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidascontratocontratista',
            name='anticipo',
        ),
        migrations.AddField(
            model_name='distribucionpago',
            name='fecha_pago',
            field=models.DateField(default='2019-03-03', verbose_name='Fecha de Pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribucionpago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Monto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribucionpago',
            name='porcentaje',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Porcentaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribucionpago',
            name='tipo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.TipoPago', verbose_name='Tipo de Pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partidascontratocontratista',
            name='dias_pactados',
            field=models.IntegerField(blank=True, default=1, verbose_name='D\xedas Pactados'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='distribucionpago',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='distribucionpago',
            name='dias_pactados',
        ),
    ]
