# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20171114_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='employer_registration_number',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='N\xfamero de Registro Patronal'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 50, 57, 252346, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 50, 57, 252380, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 50, 57, 252294, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 22, 50, 57, 255715, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
