# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20180504_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocontratista',
            name='lugar_ejecucion',
            field=models.TextField(blank=True, max_length=250, verbose_name='Lugar de Ejecuci\xf3n'),
        ),
        migrations.AlterField(
            model_name='contratocontratista',
            name='objeto_contrato',
            field=models.TextField(blank=True, max_length=250, verbose_name='Objeto de Contrato'),
        ),
        migrations.AlterField(
            model_name='contratocontratista',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
    ]
