# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20190219_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocontratista',
            name='fecha_termino_propuesta',
            field=models.DateField(null=True, verbose_name='Fecha de Termino Propuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratocontratista',
            name='fecha_termino_real',
            field=models.DateField(null=True, verbose_name='Fecha de Termino Real'),
            preserve_default=False,
        ),
    ]
