# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20171113_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressestimatelog',
            name='status',
            field=models.CharField(choices=[('N', 'Sin Revisar'), ('R', 'Revisada'), ('A', 'Aprovada')], default='N', max_length=1, verbose_name='Estado de la Bit\xe1cora'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='deduction_comments',
            field=tinymce.models.HTMLField(verbose_name='Razones por las que Hubo Deducciones'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 4, 49, 18, 500145, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='lock_status',
            field=models.CharField(choices=[('L', 'Bloqueada'), ('U', 'Desbloquada'), ('C', 'Cerrada')], default='L', max_length=1, verbose_name='Bloqueo de la Estimaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 4, 49, 18, 500166, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 4, 49, 18, 500112, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 4, 49, 18, 502309, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
