# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20190307_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconcepts',
            name='line_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida'),
            preserve_default=False,
        ),
    ]
