# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20171213_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='sat_bank2',
            new_name='sat_bank',
        ),
    ]
