# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-20 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_auto_20190220_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocontratista',
            name='dias_pactados',
        ),
    ]
