# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_auto_20171213_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='sat_bank',
        ),
    ]
