# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_contractconcepts_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractconcepts',
            name='ThisEstimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='A Esta Estimaci\xf3n'),
        ),
    ]
