# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_auto_20171114_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='services',
            field=models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='Servicios que presta'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 2, 47, 369674, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 2, 47, 369709, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 2, 47, 369621, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 23, 2, 47, 373047, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
