# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_auto_20171113_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressestimatelog',
            options={'permissions': (('change_log_status', 'Can change project log status'),), 'verbose_name_plural': 'Bit\xe1coras'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 5, 9, 40, 310539, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 5, 9, 40, 310559, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 5, 9, 40, 310509, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 5, 9, 40, 313221, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
