# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_remove_bank_sat_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SATBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=3, verbose_name='Clave Cuenta SAT')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Cuenta SAT')),
                ('business_name', models.CharField(max_length=500, verbose_name='Raz\xf3n social')),
            ],
            options={
                'verbose_name': 'Bancos del SAT.',
                'verbose_name_plural': 'Bancos del SAT.',
            },
        ),
    ]
