# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_auto_20171114_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='tax_person_type',
            field=models.CharField(choices=[('f', 'F\xedsica'), ('m', 'Moral')], default='m', max_length=1, verbose_name='Tipo de Persona'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 7, 9, 673005, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 7, 9, 673068, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 7, 9, 672880, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 23, 7, 9, 678412, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
