# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_auto_20171114_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_legal_representantive',
            field=models.BooleanField(default=False, verbose_name='Representante Legarl'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 11, 27, 379688, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 11, 27, 379721, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 11, 27, 379622, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 23, 11, 27, 382569, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
