# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_auto_20190307_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidascontratocontratista',
            name='concepts',
            field=models.ManyToManyField(through='ERP.ContractConcepts', to='ERP.Concept_Input', verbose_name='Conceptos'),
        ),
        migrations.AlterField(
            model_name='contractconcepts',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.PartidasContratoContratista', verbose_name='Contrato'),
        ),
    ]
