# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-20 04:28
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_auto_20190220_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocontratista',
            name='fecha_termino',
        ),

    ]
