# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_auto_20171114_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocontratista',
            name='payment_distribution',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Distribuci\xf3n del pago'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_legal_representantive',
            field=models.BooleanField(default=False, verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 23, 44, 208206, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 23, 44, 208231, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 23, 44, 208175, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 23, 23, 44, 210309, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
