# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-20 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_auto_20190220_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocontratista',
            name='advanced_payment',
        ),
        migrations.RemoveField(
            model_name='contratocontratista',
            name='line_item',
        ),
        migrations.RemoveField(
            model_name='contratocontratista',
            name='monto_contrato',
        ),
        migrations.RemoveField(
            model_name='contratocontratista',
            name='payment_distribution',
        ),
        migrations.RemoveField(
            model_name='contratocontratista',
            name='pdf_version',
        ),
    ]
