# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_auto_20180220_1810'),
        ('ERP', '0011_bank_sat_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='sat_bank',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='estado',
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='services',
            field=models.TextField(blank=True, default='', max_length=4096, null=True, verbose_name='Servicios que presta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ubicacion_estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ubicacion_pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ubicacion_municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ubicacion_estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ubicacion_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='pa\xeds'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='SATBank',
        ),
    ]
