# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-20 06:18
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_auto_20190220_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocontratista',
            name='advanced_payment',
            field=models.FloatField(default=0, verbose_name='Anticipio'),
        ),
        migrations.AddField(
            model_name='contratocontratista',
            name='line_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project', chained_model_field='project', default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratocontratista',
            name='monto_contrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto de Contrato'),
        ),
        migrations.AddField(
            model_name='contratocontratista',
            name='payment_distribution',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Distribuci\xf3n del pago'),
        ),
        migrations.AddField(
            model_name='contratocontratista',
            name='pdf_version',
            field=models.FileField(default=1, upload_to=ERP.models.upload_contract_file, verbose_name='Archivo PDF del contrato'),
            preserve_default=False,
        ),
    ]
