# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-13 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20190313_0035'),
    ]

    operations = [

    ]
