# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20171114_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocontratista',
            name='assigment_number',
            field=models.IntegerField(default=1, max_length=1024, verbose_name='N\xfamero de asignaci\xf3n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 28, 33, 599357, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 28, 33, 599393, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 28, 33, 599308, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 23, 28, 33, 602658, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
