# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:37
from __future__ import unicode_literals

import ERP.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0013_auto_20171114_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocontratista',
            name='pdf_version',
            field=models.FileField(default=1, upload_to=ERP.models.upload_contract_file, verbose_name='Archivo PDF del contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 37, 12, 536984, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 37, 12, 537019, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 23, 37, 12, 536902, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 23, 37, 12, 541769, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
