# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_auto_20171114_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocontratista',
            name='advanced_payment',
            field=models.FloatField(default=0, verbose_name='Anticipio'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 18, 1, 18, 99648, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 18, 1, 18, 99691, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 18, 1, 18, 99597, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 18, 1, 18, 103695, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
