# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0015_estimate_contractlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidascontratocontratista',
            name='monto_partida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Monto de la Partida'),
        ),
    ]
