# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 20:14
from __future__ import unicode_literals

import ERP.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0015_auto_20171115_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bluepint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank='', upload_to=ERP.models.upload_blueprint, verbose_name='Archivo')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='Descripci\xf3n')),
                ('upload_date', models.DateField(auto_now=True, verbose_name='Fecha de carga')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.AlterField(
            model_name='contratocontratista',
            name='assigment_number',
            field=models.IntegerField(verbose_name='N\xfamero de asignaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 200064, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 200097, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 200012, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 203781, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
