# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0016_auto_20171117_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bluepint',
            new_name='Blueprint',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 15, 17, 508195, tzinfo=utc), null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='period',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 15, 17, 508234, tzinfo=utc), null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 15, 17, 508141, tzinfo=utc), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='progressestimatelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 20, 15, 17, 516325, tzinfo=utc), null=True, verbose_name='Fecha'),
        ),
    ]
