# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-15 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0016_auto_20190315_0229'),
    ]

    operations = [

    ]
