# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_progressestimate_paid_out'),
    ]

    operations = [

    ]
