# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-23 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0019_contractconcepts_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionpago',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje'),
        ),
    ]
