# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0022_auto_20190323_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='CLABE',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='CLABE Interbancaria'),
        ),
    ]
