# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0023_contratista_clabe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEstimateConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_this_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='En esta Estimaci\xf3n')),
                ('accumulated_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Hasta esta Estimaci\xf3n')),
                ('contract_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ContractConcepts', verbose_name='Concepto')),
                ('progress_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.ProgressEstimate', verbose_name='Avance de Estimaci\xf3n')),
            ],
            options={
                'verbose_name': 'Avance F\xf1isico del Concepto',
                'verbose_name_plural': 'Avance F\xedsico de los Conceptos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='progressestimateconcepts',
            unique_together=set([('progress_estimate', 'contract_concept')]),
        ),
    ]
