# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-09 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0024_auto_20190404_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='contrato',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='ERP.ContratoContratista', verbose_name='Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='line_item',
            field=models.ForeignKey(default=1214, on_delete=django.db.models.deletion.CASCADE, to='ERP.LineItem', verbose_name='Partida'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together=set([('project', 'year', 'month', 'line_item', 'contrato')]),
        ),
    ]
