# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-09 18:26
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0025_auto_20190509_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='generator_file',
            field=models.FileField(blank=True, null=True, upload_to=ERP.models.content_file_generador, verbose_name='Justificaci\xf3n'),
        ),
    ]
