# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-14 17:03
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0026_estimate_generator_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='generator_file',
            field=models.FileField(blank=True, null=True, upload_to=ERP.models.content_file_anticipo, verbose_name='Justificaci\xf3n'),
        ),
    ]
