# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-20 19:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0027_auto_20190514_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='Total_paid',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, max_length=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Total Pagado'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='advance_payment_amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Anticipo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='contract_amount_override',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Total Real'),
        ),
    ]
