# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 04:18
from __future__ import unicode_literals

import ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0029_auto_20190621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressestimate',
            name='amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, validators=[ERP.models.decimal_ammount], verbose_name='Monto ($)'),
        ),
    ]
