# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0030_auto_20190624_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressestimate',
            name='amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, verbose_name='Monto ($)'),
        ),
    ]
