# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 05:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0031_auto_20190624_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressestimate',
            name='amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20, validators=[django.core.validators.RegexValidator(message='Favor de verificar el .', regex='^\\d{0,10}(\\.\\d{0,9})?$')], verbose_name='Monto ($)'),
        ),
    ]
