# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0032_auto_20190624_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionpago',
            name='monto',
            field=models.DecimalField(decimal_places=9, max_digits=50, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='distribucionpago',
            name='porcentaje',
            field=models.DecimalField(decimal_places=9, max_digits=13, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='partidascontratocontratista',
            name='monto_partida',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, verbose_name='Monto de la Partida'),
        ),
    ]
