# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='InternalCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Empresa Interna',
                'verbose_name_plural': 'Empresas Internas',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='internal_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa Interna'),
        ),
    ]
