# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25, verbose_name='N\xfamero de Cuenta'),
        ),
    ]
