# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='accounting_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Account', verbose_name='Cuenta Contable'),
            preserve_default=False,
        ),
    ]
