# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemaccount',
            options={'verbose_name': 'Rubro de Cuenta', 'verbose_name_plural': 'Rubros de Cuentas'},
        ),
    ]
