# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='internal_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa Interna'),
        ),
    ]
