# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-16 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='item',
        ),
    ]
