# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-07 07:15
from __future__ import unicode_literals

import SharedCatalogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcompany',
            name='logo_file',
            field=models.FileField(null=True, upload_to=SharedCatalogs.models.uploaded_internal_company, verbose_name='Logo de Empresa'),
        ),
    ]
