# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0002_bank_accounting_account'),
    ]
