# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-08 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0002_internalcompany_logo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcompany',
            name='logo_file',
        ),
    ]
