# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20181120_2028'),
    ]

    operations = [

    ]
