# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-20 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20180220_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='sat_bank',
        ),
    ]
