# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20171215_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.BigIntegerField(verbose_name='N\xfamero de Cuenta'),
        ),
    ]
