# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0004_auto_20171216_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('A', 'Acumulativa'), ('D', 'Detalle')], default='A', max_length=1, verbose_name='Tipo de Cuenta'),
            preserve_default=False,
        )
    ]
