# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-27 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0004_auto_20181123_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
