# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:27
from __future__ import unicode_literals

import HumanResources.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='\xc1rea')),
            ],
            options={
                'verbose_name': '\xc1rea',
                'verbose_name_plural': '\xc1reas',
            },
        ),
        migrations.CreateModel(
            name='CheckerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_type', models.IntegerField(choices=[(1, 'Autom\xe1tico'), (2, 'Manual')], default=1, verbose_name='Tipo de Checador')),
                ('checks_entry', models.BooleanField(default=True, verbose_name='Checa Entrada')),
                ('checks_exit', models.BooleanField(default=True, verbose_name='Checa Salida')),
            ],
            options={
                'verbose_name': 'Datos de Checador del Empleado',
                'verbose_name_plural': 'Datos de Checador del Empleado',
            },
        ),
        migrations.CreateModel(
            name='CurrentEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Licenciatura'), (2, 'Maestr\xeda'), (3, 'Doctorado')], default=1, verbose_name='Tipo de Educaci\xf3n')),
                ('name', models.CharField(max_length=2048, verbose_name='Nombre')),
                ('institution', models.CharField(max_length=1024, verbose_name='Instituci\xf3n')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('monday', models.BooleanField(default=False, verbose_name='Lunes')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Mi\xe9rcoles')),
                ('thursday', models.BooleanField(default=False, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=False, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=False, verbose_name='S\xe1bado')),
            ],
            options={
                'verbose_name': 'Formaci\xf3n Acad\xe9mica Actual del Empleado',
                'verbose_name_plural': 'Formaci\xf3n Acad\xe9mica Actual del Empleado',
            },
        ),
        migrations.CreateModel(
            name='CurrentEducationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=HumanResources.models.upload_employee_current_education_document, verbose_name='Archivo')),
                ('comments', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Comentarios')),
                ('current_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.CurrentEducation', verbose_name='Formaci\xf3n Actual del Empleado')),
            ],
            options={
                'verbose_name': 'Documento de la Formaci\xf3n Actual del Empleado',
                'verbose_name_plural': 'Documentos de la Formaci\xf3n Actual del Empleado',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Direcci\xf3n')),
            ],
            options={
                'verbose_name': 'Direcci\xf3n',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Etiquetas',
                'verbose_name_plural': 'Tipo de Documento',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Licenciatura'), (2, 'Maestr\xeda'), (3, 'Doctorado')], default=1, verbose_name='Tipo de Educaci\xf3n')),
                ('name', models.CharField(max_length=2048, verbose_name='Nombre')),
                ('institution', models.CharField(max_length=1024, verbose_name='Instituci\xf3n')),
                ('license_code', models.CharField(max_length=512, verbose_name='C\xf3digo o N\xfamero de C\xe9dula')),
                ('evidence', models.FileField(blank=True, null=True, upload_to=HumanResources.models.upload_employee_education_document, verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Formaci\xf3n Acad\xe9mica del Empleado',
                'verbose_name_plural': 'Formaci\xf3n Acad\xe9mica del Empleado',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N\xfamero de Tel\xe9fono')),
                ('cellphone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N\xfamero de Celular')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electr\xf3nico')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_key', models.CharField(max_length=64, verbose_name='Clave del Empleado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('type', models.IntegerField(choices=[(1, 'Empleado Tipo A'), (2, 'Empleado Tipo B')], default=1, verbose_name='Tipo de Empleando')),
                ('registry_date', models.DateField(default=datetime.datetime(2017, 11, 8, 21, 27, 11, 895650, tzinfo=utc), verbose_name='Fecha de Registro')),
                ('status', models.IntegerField(choices=[(1, 'Estatus A del Empleado'), (2, 'Estatus B del Empleado')], default=1, verbose_name='Estatus del Empleado')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('birthplace', models.CharField(max_length=255, verbose_name='Lugar de Nacimiento')),
                ('gender', models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')], default=1, verbose_name='G\xe9nero')),
                ('marital_status', models.IntegerField(choices=[(1, 'Soltero'), (2, 'Casado')], default=1, verbose_name='Estado Civil')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Tel\xe9fono')),
                ('cellphone_number', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('office_number', models.CharField(blank=True, max_length=20, verbose_name='Tel\xe9fono de Oficina')),
                ('extension_number', models.CharField(blank=True, max_length=10, verbose_name='N\xfamero de Extensi\xf3n')),
                ('personal_email', models.CharField(max_length=255, null=True, verbose_name='Correo Electr\xf3nico Personal')),
                ('work_email', models.CharField(max_length=255, verbose_name='Correo Electr\xf3nico Laboral')),
                ('social_security_number', models.CharField(max_length=20, verbose_name='N\xfamero de Seguro Social')),
                ('colony', models.CharField(max_length=255, verbose_name='Colonia')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('outdoor_number', models.CharField(max_length=10, verbose_name='No. Exterior')),
                ('indoor_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='No. Interior')),
                ('zip_code', models.CharField(max_length=5, verbose_name='C\xf3digo Postal')),
                ('blood_type', models.IntegerField(choices=[(1, 'O Negativo'), (2, 'O Positivo')], default=1, verbose_name='Tipo Sangu\xedneo')),
                ('driving_license_number', models.CharField(blank=True, max_length=20, verbose_name='N\xfamero de Licencia de Conducir')),
                ('driving_license_expiry_date', models.DateField(blank=True, verbose_name='Fecha de Expiraci\xf3n de la Licencia de Conducir')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Pais', verbose_name='Pa\xeds')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='ERP.Estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 11, 8, 21, 27, 11, 917947, tzinfo=utc), verbose_name='Fecha')),
                ('entry_time', models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 27, 11, 917989, tzinfo=utc), verbose_name='Hora de Entrada')),
                ('exit_time', models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 27, 11, 918012, tzinfo=utc), verbose_name='Hora de Salida')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_key', models.CharField(max_length=128, verbose_name='Clave del Contrato')),
                ('description', models.CharField(max_length=4096, verbose_name='Descripci\xf3n del Contrato')),
                ('specifications', models.CharField(max_length=4096, verbose_name='Especificaciones del Contrato')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de T\xe9rmino')),
                ('base_salary', models.FloatField(verbose_name='Salario')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Contrato del Empleado',
                'verbose_name_plural': 'Contratos del Empleado',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=HumanResources.models.upload_employee_document, verbose_name='Archivo')),
                ('comments', models.CharField(max_length=2048, verbose_name='Comentarios')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.DocumentType', verbose_name='Tipo de Documento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Documento Probatorio',
                'verbose_name_plural': 'Documentos Probatorios',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDropOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Baja')),
                ('type', models.IntegerField(choices=[(1, 'Despido'), (2, 'Incapacidad')], default=1, verbose_name='Tipo de Baja')),
                ('reason', models.CharField(blank=True, max_length=4096, verbose_name='Motivo')),
                ('severance_pay', models.FloatField(null=True, verbose_name='Liquidaci\xf3n')),
                ('observations', models.CharField(max_length=4096, null=True, verbose_name='Observaciones')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Baja de Empleado',
                'verbose_name_plural': 'Bajas de Empleado',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Etiqueta del Empleado',
                'verbose_name_plural': 'Etiquetas del Empleado',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Cantidad')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Pr\xe9stamo',
                'verbose_name_plural': 'Pr\xe9stamos',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('relationship', models.CharField(blank=True, max_length=128, verbose_name='Parentesco')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Vacante de Empleos',
                'verbose_name_plural': 'Vacante de Puesto',
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=2048, verbose_name='Puesto')),
                ('abilities', models.CharField(blank=True, max_length=2048, verbose_name='Habilidades')),
                ('aptitudes', models.CharField(blank=True, max_length=2048, verbose_name='Aptitudes')),
                ('knowledge', models.CharField(blank=True, max_length=2048, verbose_name='Conocimientos')),
                ('competitions', models.CharField(blank=True, max_length=2048, verbose_name='Competencias')),
                ('scholarship', models.CharField(blank=True, max_length=2048, verbose_name='Escolaridad ')),
                ('experience', models.CharField(blank=True, max_length=2048, verbose_name='Experiencia')),
                ('entry_time', models.TimeField(verbose_name='Horario de Entrada')),
                ('exit_time', models.TimeField(verbose_name='Horario de Salida')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('monday', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Mi\xe9rcoles')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=True, verbose_name='S\xe1bado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Department', verbose_name='Departamento')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n')),
            ],
            options={
                'verbose_name': 'Perfil de Puesto',
                'verbose_name_plural': 'Perfiles de Puesto',
            },
        ),
        migrations.CreateModel(
            name='Subdirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Subdirecci\xf3n')),
            ],
            options={
                'verbose_name': 'Subdirecci\xf3n',
                'verbose_name_plural': 'Subdirecciones',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre de la Etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='R\xe9gimen Fiscal')),
            ],
            options={
                'verbose_name': 'R\xe9gimen Fiscal',
                'verbose_name_plural': 'Reg\xedmenes Fiscales',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Nombre de la Prueba')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
            },
        ),
        migrations.CreateModel(
            name='TestApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='Fecha de Aplicaci\xf3n')),
                ('result', models.CharField(max_length=512, verbose_name='Resultado')),
                ('comments', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Comentarios')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Test', verbose_name='Prueba')),
            ],
            options={
                'verbose_name': 'Aplicaci\xf3n de Prueba del Empleado',
                'verbose_name_plural': 'Aplicaciones de Pruebas del Empleado',
            },
        ),
        migrations.CreateModel(
            name='WorkReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Persona que Hace la Referencia')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='Apellido Paterno de la Persona que Hace la Referencia')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='Apellido Materno de la Persona que Hace la Referencia')),
                ('company_name', models.CharField(max_length=255, verbose_name='Empresa')),
                ('first_phone_number', models.CharField(max_length=20, verbose_name='N\xfamero de Tel\xe9fono #1')),
                ('second_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N\xfamero de Tel\xe9fono #2')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electr\xf3nico')),
                ('notes', models.CharField(max_length=2048, null=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Referencia Laboral',
                'verbose_name_plural': 'Referencias Laborales',
            },
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='subdirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n'),
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobProfile', verbose_name='Perfil de Empleado'),
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='parent_job_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobInstance', verbose_name='Jefe Inmediato'),
        ),
        migrations.AddField(
            model_name='employeehastag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Tag', verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tags',
            field=models.ManyToManyField(through='HumanResources.EmployeeHasTag', to='HumanResources.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.TaxRegime', verbose_name='R\xe9gimen Fiscal'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tests',
            field=models.ManyToManyField(through='HumanResources.TestApplication', to='HumanResources.Test', verbose_name='Pruebas'),
        ),
        migrations.AddField(
            model_name='employee',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='ERP.Municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='currenteducation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='checkerdata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='employeehastag',
            unique_together=set([('employee', 'tag')]),
        ),
    ]
