# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefinancialdata',
            name='bank',
            field=models.CharField(choices=[('1', 'BANCOMER'), ('2', 'BANAMEX'), ('3', 'BANORTE'), ('4', 'SANTANDER'), ('5', 'HSBC')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 7, 47, 7, 911374, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 7, 47, 7, 934337, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 13, 7, 47, 7, 934375, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 13, 7, 47, 7, 934399, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
