# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infonavitdata',
            name='employee_financial_data',
        ),
        migrations.AddField(
            model_name='infonavitdata',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
            preserve_default=False,
        ),
    ]
