# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsdeductions',
            name='category',
            field=models.CharField(choices=[('F', 'Fija'), ('V', 'Variable')], default='F', max_length=1, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='earningsdeductions',
            name='taxable',
            field=models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Gravable'),
        ),
        migrations.AddField(
            model_name='earningsdeductions',
            name='type',
            field=models.CharField(choices=[('D', 'Deducci\xf3n'), ('P', 'Percepci\xf3n')], default='D', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 50, 20, 395309, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 23, 50, 20, 423113, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 13, 23, 50, 20, 423183, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 13, 23, 50, 20, 423240, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
