# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='\xc1rea')),
            ],
            options={
                'verbose_name': '\xc1rea',
                'verbose_name_plural': '\xc1reas',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Direcci\xf3n')),
            ],
            options={
                'verbose_name': 'Direcci\xf3n',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=2048, verbose_name='Puesto')),
                ('abilities', models.CharField(blank=True, max_length=2048, verbose_name='Habilidades')),
                ('aptitudes', models.CharField(blank=True, max_length=2048, verbose_name='Aptitudes')),
                ('knowledge', models.CharField(blank=True, max_length=2048, verbose_name='Conocimientos')),
                ('competitions', models.CharField(blank=True, max_length=2048, verbose_name='Competencias')),
                ('scholarship', models.CharField(blank=True, max_length=2048, verbose_name='Escolaridad ')),
                ('experience', models.CharField(blank=True, max_length=2048, verbose_name='Experiencia')),
                ('entry_time', models.TimeField(verbose_name='Horario de Entrada')),
                ('exit_time', models.TimeField(verbose_name='Horario de Salida')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('monday', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Mi\xe9rcoles')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=True, verbose_name='S\xe1bado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Department', verbose_name='Departamento')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n')),
            ],
            options={
                'verbose_name': 'Perfil de Puesto',
                'verbose_name_plural': 'Perfiles de Puesto',
            },
        ),
        migrations.CreateModel(
            name='Subdirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Subdirecci\xf3n')),
            ],
            options={
                'verbose_name': 'Subdirecci\xf3n',
                'verbose_name_plural': 'Subdirecciones',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 21, 42, 12, 69642, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 21, 42, 12, 90406, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 6, 21, 42, 12, 90453, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 6, 21, 42, 12, 90489, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='subdirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n'),
        ),
    ]
