# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [

    ]
