# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 11, 6, 21, 4, 20, 674934, tzinfo=utc), verbose_name='Fecha')),
                ('entry_time', models.TimeField(default=datetime.datetime(2017, 11, 6, 21, 4, 20, 675012, tzinfo=utc), verbose_name='Hora de Entrada')),
                ('exit_time', models.TimeField(default=datetime.datetime(2017, 11, 6, 21, 4, 20, 675073, tzinfo=utc), verbose_name='Hora de Salida')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Pr\xe9stamo',
                'verbose_name_plural': 'Pr\xe9stamos',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 21, 4, 20, 643107, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='employeeassistance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
    ]
