# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-14 17:27
from __future__ import unicode_literals

import HumanResources.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedEmployeeAssistanceChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_file', models.FileField(null=True, upload_to=HumanResources.models.uploaded_employees_assistance_destination, verbose_name='Archivo de Asistencias')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollPeriod', verbose_name='Periodo de n\xf3mina')),
            ],
            options={
                'verbose_name': 'Archivo de asistencias',
                'verbose_name_plural': 'Archivos de Asistencias',
            },
        ),
    ]
