# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='maximumsalary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Salario M\xe1ximo'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='minimumsalary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Salario M\xednimo'),
        ),
    ]
