# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-06 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_auto_20171106_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobProfile', verbose_name='Perfil de Empleado')),
                ('parent_job_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobInstance', verbose_name='Jefe Inmediato')),
            ],
            options={
                'verbose_name': 'Vacante de Empleos',
                'verbose_name_plural': 'Vacante de Puesto',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 22, 20, 38, 841210, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 22, 20, 38, 866758, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 6, 22, 20, 38, 866846, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 6, 22, 20, 38, 866896, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
