# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_periodicity_total_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonavitdata',
            name='discount_amount',
            field=models.FloatField(default=0.0, verbose_name='Monto de Descuento*'),
        ),
    ]
