# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_employeeloandetail_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeloandetail',
            name='deduction',
        ),
    ]
