# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_auto_20171102_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthplace',
            field=models.CharField(max_length=255, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 2, 5, 26, 9, 44276, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
