# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-26 21:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_auto_20180220_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_requirements', tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Requisitos M\xednimos')),
                ('characteristics', tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Caracter\xedsticas del Puesto')),
                ('vacancy_number', models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Department', verbose_name='Departamento')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n')),
                ('subdirection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n')),
            ],
        ),
        migrations.AlterField(
            model_name='employeedropout',
            name='observations',
            field=tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeearningsdeductions',
            unique_together=set([('concept', 'employee')]),
        ),
    ]
