# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_auto_20180220_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='key',
            field=models.CharField(default=0, max_length=512, verbose_name='Clave de la Prueba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='notes',
            field=models.CharField(default='', max_length=1024, verbose_name='Notas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedropout',
            name='observations',
            field=tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeearningsdeductions',
            unique_together=set([('concept', 'employee')]),
        ),
    ]
