# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_remove_periodicity_total_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicity',
            name='total_payments',
            field=models.IntegerField(default=0, verbose_name='Numero de pagos'),
            preserve_default=False,
        ),
    ]
