# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HumanResources', '0002_auto_20181129_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso a Direcci\xf3n',
                'verbose_name_plural': 'Accesos a Direcci\xf3n',
            },
        ),
        migrations.AlterUniqueTogether(
            name='accesstodirection',
            unique_together=set([('user', 'direction')]),
        ),
    ]
