# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_auto_20180501_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsdeductions',
            name='penalty',
            field=models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Penalizaci\xf3n'),
        ),
    ]
