# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_uploadedemployeeassistancechecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedemployeeassistancehistory',
            name='date_processed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualizaci\xf3n'),
        ),
    ]
