# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-04 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('HumanResources', '0003_auto_20181129_2049'),
    ]

    operations = [
    ]
