# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0001_initial'),
        ('HumanResources', '0003_auto_20180223_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsdeductions',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Account', verbose_name='Cuenta'),
            preserve_default=False,
        ),
    ]
