# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_auto_20171114_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefinancialdata',
            name='bank',
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 3, 58, 882601, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 3, 58, 907518, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 14, 22, 3, 58, 907568, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 14, 22, 3, 58, 907610, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
