# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_auto_20171113_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 21, 10, 54, 791690, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 13, 21, 10, 54, 830764, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 13, 21, 10, 54, 830815, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 13, 21, 10, 54, 830863, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='bank',
            field=models.CharField(choices=[('1', 'BANCOMER'), ('2', 'BANAMEX'), ('3', 'BANORTE'), ('4', 'SANTANDER'), ('5', 'HSBC')], max_length=1),
        ),
        migrations.AlterField(
            model_name='payrollgroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Proyecto'),
        ),
    ]
