# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-26 22:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_auto_20180226_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequisition',
            name='description',
            field=models.CharField(default='Auxiliar Contable', max_length=256, verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
