# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 02:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_auto_20180502_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeloandetail',
            name='deduction',
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
