# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_periodicity_total_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecontract', to='HumanResources.Employee', verbose_name='Empleado'),
        ),
    ]
