# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_periodicity_total_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocesseddetail',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
