# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-28 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_uploadedemployeeassistancehistory_date_processed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeefinancialdata',
            unique_together=set([('account_type', 'employee')]),
        ),
    ]
