# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_earningsdeductions_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsdeductions',
            name='law_type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.IntegerField(choices=[(1, 'Empleado Tipo A'), (2, 'Empleado Tipo B')], default=1, verbose_name='Tipo de Empleado'),
        ),
    ]
