# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_auto_20171102_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_type',
            field=models.IntegerField(choices=[(1, 'O Negativo'), (2, 'O Positivo')], default=1, verbose_name='Tipo Sangu\xedneo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 2, 5, 28, 44, 285264, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
