# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-06 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0003_auto_20171106_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 22, 23, 37, 496506, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 6, 22, 23, 37, 525665, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 6, 22, 23, 37, 525722, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 6, 22, 23, 37, 525791, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='parent_job_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobInstance', verbose_name='Jefe Inmediato'),
        ),
    ]
