# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-07 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_auto_20181218_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='risk_type',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Tipo de Riesgo'),
        ),
    ]
