# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 20:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HumanResources', '0004_auto_20180226_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerequisition',
            options={'verbose_name': 'Requisici\xf3n de Personal', 'verbose_name_plural': 'Requisiciones de Personal'},
        ),
        migrations.AddField(
            model_name='employeerequisition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por:'),
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
