# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-09 06:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_employeeloandetail_deduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeloandetail',
            options={'verbose_name': 'Pr\xe9stamo Detalle', 'verbose_name_plural': 'Pr\xe9stamos Detalle'},
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeloandetail',
            unique_together=set([('employeeloan', 'period')]),
        ),
    ]
