# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 02:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_auto_20180502_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloandetail',
            name='deduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EmployeeEarningsDeductionsbyPeriod', verbose_name='Deduction'),
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
