# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-05 20:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_auto_20181205_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloandetail',
            name='period',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='payroll_group', chained_model_field='payroll_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollPeriod', verbose_name='Periodo'),
        ),
    ]
