# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-25 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_auto_20180224_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsdeductions',
            name='accounting_account',
        ),
        migrations.AlterField(
            model_name='earningsdeductions',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Account', verbose_name='Cuenta'),
        ),
    ]
