# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20171114_2206'),
        ('HumanResources', '0004_auto_20171114_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefinancialdata',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Bank', verbose_name='Banco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 6, 31, 529826, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 22, 6, 31, 550409, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 14, 22, 6, 31, 550443, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 14, 22, 6, 31, 550470, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
