# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_auto_20171108_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('1', 'BANCOMER'), ('2', 'BANAMEX'), ('3', 'BANORTE'), ('4', 'SANTANDER'), ('5', 'HSBC')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 28, 2, 890168, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 28, 2, 912071, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 28, 2, 912116, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 28, 2, 912152, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
