# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-27 22:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_auto_20180227_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollPeriodExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollPeriod', verbose_name='Periodo de N\xf3mina')),
            ],
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
        migrations.AlterField(
            model_name='payrolltype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='exclusions',
            field=models.ManyToManyField(through='HumanResources.EmployeePayrollPeriodExclusion', to='HumanResources.Employee'),
        ),
    ]
