# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-05 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_auto_20181205_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeloandetail',
            unique_together=set([]),
        ),
    ]
