# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_auto_20180502_0237'),
        ('HumanResources', '0004_auto_20180502_1514'),
    ]

    operations = [
    ]
