# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0004_auto_20190114_1453'),
        ('HumanResources', '0005_employee_risk_type'),
    ]

    operations = [
    ]
