# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '__first__'),
        ('HumanResources', '0005_auto_20171108_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePositionDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Termino')),
                ('physical_location', models.CharField(blank=True, max_length=250, verbose_name='Ubicaci\xf3n F\xedsica')),
                ('insurance_type', models.CharField(max_length=100, null=True, verbose_name='Tipo de Seguro')),
                ('insurance_number', models.CharField(max_length=100, null=True, verbose_name='N\xfamero de Seguro')),
                ('entry_time', models.TimeField(null=True, verbose_name='Hora de Entrada')),
                ('departure_time', models.TimeField(null=True, verbose_name='Hora de Salida')),
                ('observations', models.CharField(max_length=500, null=True, verbose_name='Observaciones')),
                ('monday', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Mi\xe9rcoles')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=True, verbose_name='S\xe1bado')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Department', verbose_name='Departamento')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n')),
            ],
            options={
                'verbose_name': 'Descripci\xf3n de Puesto del Empleado',
                'verbose_name_plural': 'Descripci\xf3n de Puesto del Empleado',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 28, 13, 131281, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 28, 13, 160083, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 28, 13, 160125, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 28, 13, 160148, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='employeepositiondescription',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='employeepositiondescription',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobProfile', verbose_name='Puesto'),
        ),
        migrations.AddField(
            model_name='employeepositiondescription',
            name='payroll_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PAYROLL_CLASIFICATION', verbose_name='Clasificaci\xf3n de N\xf3mina'),
        ),
        migrations.AddField(
            model_name='employeepositiondescription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='employeepositiondescription',
            name='subdirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n'),
        ),
    ]
