# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_auto_20171114_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='week',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='year',
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 245507, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 294033, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 294080, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 17, 20, 14, 53, 294116, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='payrollgroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Proyecto'),
        ),
    ]
