# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_auto_20180225_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Pruebas a Empleados', 'verbose_name_plural': 'Pruebas a Empleados'},
        ),
    ]
