# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0005_auto_20171102_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, verbose_name='Fecha de Expiraci\xf3n de la Licencia de Conducir'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='N\xfamero de Licencia de Conducir'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 2, 5, 35, 17, 608186, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
