# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_merge_20190120_1712'),
    ]

    operations = [

        migrations.AddField(
            model_name='payrollprocesseddetail',
            name='earningdeduction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningsDeductions', verbose_name='Id_PercepcionDeduccion'),
            preserve_default=False,
        ),

    ]
