# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_auto_20171108_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFinancialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=0, max_length=20, verbose_name='N\xfamero de Cuenta')),
                ('CLABE', models.IntegerField(default=0, max_length=20, verbose_name='CLABE')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Salario Mensual')),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Salario Diario')),
                ('aggregate_daily_salary', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Salario Diario Acumulado')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Bank', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Datos Financieros del Empleado',
                'verbose_name_plural': 'Datos Financieros del Empleado',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 28, 46, 228275, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 28, 46, 254419, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 28, 46, 254458, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 28, 46, 254485, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='employeefinancialdata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='employeefinancialdata',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Payment_Method', verbose_name='Forma de Pago'),
        ),
    ]
