# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-24 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_auto_20180524_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequisition',
            name='reason',
            field=tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Raz\xf3n'),
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
