# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_auto_20171102_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='employee',
            name='extension_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='N\xfamero de Extensi\xf3n'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tel\xe9fono de Oficina'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 2, 5, 37, 0, 247678, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
