# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0006_auto_20180227_2218'),
        ('HumanResources', '0006_auto_20180226_0915'),
    ]

    operations = [
    ]
