# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_auto_20171108_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfonavitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infonavit_credit_number', models.CharField(max_length=30, verbose_name='N\xfamero de Cr\xe9dito')),
                ('discount_type', models.CharField(max_length=30, verbose_name='Tipo de Descuento')),
                ('discount_amount', models.CharField(max_length=30, verbose_name='Monto de Descuento')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('credit_term', models.CharField(max_length=200, verbose_name='Duraci\xf3n de Cr\xe9dito')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Datos del Infonavit del Empleado',
                'verbose_name_plural': 'Datos del Infonavit del Empleado',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 30, 13, 250052, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 30, 13, 288719, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 30, 13, 288767, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 30, 13, 288801, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='infonavitdata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
    ]
