# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_merge_20180307_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='jobdescription',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Descripci\xf3n del Puesto '),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='minimumrequirements',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Requisitos m\xednimos'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepayrollperiodexclusion',
            unique_together=set([('employee', 'payroll_period')]),
        ),
    ]
