# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_auto_20171102_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Correo Electr\xf3nico Personal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 2, 5, 38, 56, 978064, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
