# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_merge_20180307_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepayrollperiodexclusion',
            unique_together=set([('employee', 'payroll_period')]),
        ),
    ]
