# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_auto_20190120_1713'),
    ]

    operations = [

    ]
