# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_auto_20181115_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonavitdata',
            name='employee_financial_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EmployeeFinancialData'),
        ),
    ]
