# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 00:46
from __future__ import unicode_literals

import HumanResources.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_auto_20171102_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=HumanResources.models.upload_employee_education_document, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='indoor_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No. Interior'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 3, 0, 46, 8, 797809, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
