# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 15:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_auto_20180420_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_security_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de Seguro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(max_length=20, verbose_name='N\xfamero de P\xf3liza de Seguro'),
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
