# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_payrollprocesseddetail_earningdeduction_key'),
    ]

    operations = [

    ]
