# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0009_auto_20190120_1719'),
    ]

    operations = [

    ]
