# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0009_auto_20171108_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsDeductionsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_deductions_category', models.CharField(choices=[('F', 'Fija'), ('V', 'Variable')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 2, 115092, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 2, 139481, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 2, 139529, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 2, 139563, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
