# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-08 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0009_auto_20181206_1911'),
        ('HumanResources', '0005_auto_20181204_2035'),
    ]

    operations = [
    ]
