# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_auto_20180420_1515'),
        ('HumanResources', '0009_auto_20180420_1521'),
    ]

    operations = [
    ]
