# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0010_merge_20180420_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='minimumrequirements',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Requisitos M\xednimos del Puesto'),
        ),
    ]
