# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0010_auto_20171108_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningDeductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_deduction_type', models.CharField(choices=[('D', 'Deducci\xf3n'), ('P', 'Percepci\xf3n')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 12, 511481, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 12, 535701, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 12, 535753, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 12, 535788, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
