# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0010_merge_20181208_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_key',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='La CURP que proporcionas es incorrecta.', regex='^[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM]{1}(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{1}[0-9]{1}$')], verbose_name='Clave (RFC)*'),
        ),
    ]
