# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 19:51
from __future__ import unicode_literals

import HumanResources.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0002_remove_account_item'),
        ('HumanResources', '0010_auto_20181115_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenteducation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado*'),
        ),
        migrations.AlterField(
            model_name='currenteducation',
            name='institution',
            field=models.CharField(max_length=1024, verbose_name='Instituci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='currenteducation',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Nombre de la formaci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='currenteducationdocument',
            name='comments',
            field=models.CharField(blank=True, max_length=2048, null=True, validators=[django.core.validators.RegexValidator(message='\xc9ste campo no acepta caracateres como: +*/{] .', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='currenteducationdocument',
            name='current_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.CurrentEducation', verbose_name='Formaci\xf3n Actual del Empleado*'),
        ),
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado\xa1'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=1024, verbose_name='Instituci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='education',
            name='license_code',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='C\xf3digo o N\xfamero de C\xe9dula'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=2048, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Nombre de la Profesi\xf3n*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='N\xfamero de Celular'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='colony',
            field=models.CharField(max_length=255, verbose_name='Colonia*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el correo electr\xf3nico que proporcionas sea correcto.', regex="\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*")], verbose_name='Correo Electr\xf3nico'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Paterno*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='outdoor_number',
            field=models.CharField(max_length=10, verbose_name='No. Exterior*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='N\xfamero de Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='second_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Materno*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Calle*'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros.', regex='[0-9]')], verbose_name='C\xf3digo Postal*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de Nacimiento*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthplace',
            field=models.CharField(max_length=255, verbose_name='Lugar de Nacimiento*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='colony',
            field=models.CharField(max_length=255, verbose_name='Colonia*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='curp',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='La CURP que proporcionas es incorrecta.', regex='^[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM]{1}(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{1}[0-9]{1}$')], verbose_name='CURP*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiraci\xf3n de Licencia para Conducir'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_key',
            field=models.CharField(max_length=64, verbose_name='Clave*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='extension_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros.', regex='[0-9]')], verbose_name='N\xfamero de Extensi\xf3n'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Paterno*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Tel\xe9fono de Oficina'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='outdoor_number',
            field=models.CharField(max_length=10, verbose_name='No. Exterior*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el correo electr\xf3nico que proporcionas sea correcto.', regex="\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*")], verbose_name='Correo Electr\xf3nico Personal*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Tel\xe9fono*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(upload_to=HumanResources.models.upload_employee_photo, verbose_name='Foto*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RFC que proporcionas es incorrecto.', regex='^([A-Z\xd1&]{3,4}) ?(?:- ?)?(\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])) ?(?:- ?)?([A-Z\\d]{2})([A\\d])$')], verbose_name='RFC*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Materno*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(max_length=20, verbose_name='N\xfamero de P\xf3liza de Seguro*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado', verbose_name='Estado*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Calle*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.TaxRegime', verbose_name='R\xe9gimen Fiscal*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio', verbose_name='Municipio*'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.IntegerField(choices=[(1, 'Administrativo'), (2, 'Operativo')], default=1, verbose_name='Tipo de Empleado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el correo electr\xf3nico que proporcionas sea correcto.', regex="\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*")], verbose_name='Correo Electr\xf3nico Laboral'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros.', regex='[0-9]')], verbose_name='C\xf3digo Postal*'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='comments',
            field=models.CharField(max_length=2048, validators=[django.core.validators.RegexValidator(message='\xc9ste campo no acepta caracateres como: +*/{] .', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Comentarios*'),
        ),
        migrations.AlterField(
            model_name='employeeearningsdeductions',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Monto*'),
        ),
        migrations.AlterField(
            model_name='employeeearningsdeductions',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningsDeductions', verbose_name='Concepto*'),
        ),
        migrations.AlterField(
            model_name='employeeearningsdeductions',
            name='date',
            field=models.DateField(verbose_name='Fecha*'),
        ),
        migrations.AlterField(
            model_name='employeeearningsdeductionsbyperiod',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='employeeearningsdeductionsbyperiod',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningsDeductions', verbose_name='Conceptos'),
        ),
        migrations.AlterField(
            model_name='employeeearningsdeductionsbyperiod',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='CLABE',
            field=models.CharField(default=0, max_length=40, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros.', regex='[0-9]')], verbose_name='Clave Interbancaria (CLABE)'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='account_number',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator(message='Este campo solo acepta n\xfameros.', regex='[0-9]')], verbose_name='N\xfamero de Cuenta'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='aggregate_daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Salario Diario Acumulado'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.SATBank', verbose_name='Banco*'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Empresa/Proyecto*'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Termino'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.JobProfile', verbose_name='Puesto*'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='observations',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='\xc9ste campo no acepta caracateres como: +*/{] .', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Observaciones*'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='payroll_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollGroup', verbose_name='Grupo de N\xf3mina*'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='subdirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='career',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Profesi\xf3n'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado*'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Paterno*'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='N\xfamero de Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='second_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Materno*'),
        ),
        migrations.AlterField(
            model_name='infonavitdata',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='\xc9ste campo no acepta caracateres como: +*/{] .', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='infonavitdata',
            name='infonavit_credit_number',
            field=models.CharField(max_length=30, verbose_name='N\xfamero de Cr\xe9dito*'),
        ),
        migrations.AlterField(
            model_name='testapplication',
            name='comments',
            field=models.CharField(blank=True, max_length=2048, null=True, validators=[django.core.validators.RegexValidator(message='\xc9ste campo no acepta caracateres como: +*/{] .', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Empresa*'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el correo electr\xf3nico que proporcionas sea correcto.', regex="\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*")], verbose_name='Correo Electr\xf3nico'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado*'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='first_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Paterno*'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='first_phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='N\xfamero de Tel\xe9fono #1'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='notes',
            field=models.CharField(max_length=2048, null=True, validators=[django.core.validators.RegexValidator(message='\xc9ste campo no acepta caracateres como: +*/{] .', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='second_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tu nombre no es correcto.', regex="[a-zA-Z\xe0\xe1\xe2\xe4\xe3\xe5\u0105\u010d\u0107\u0119\xe8\xe9\xea\xeb\u0117\u012f\xec\xed\xee\xef\u0142\u0144\xf2\xf3\xf4\xf6\xf5\xf8\xf9\xfa\xfb\xfc\u0173\u016b\xff\xfd\u017c\u017a\xf1\xe7\u010d\u0161\u017e\xc0\xc1\xc2\xc4\xc3\xc5\u0104\u0106\u010c\u0116\u0118\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\u012e\u0141\u0143\xd2\xd3\xd4\xd6\xd5\xd8\xd9\xda\xdb\xdc\u0172\u016a\u0178\xdd\u017b\u0179\xd1\xdf\xc7\u0152\xc6\u010c\u0160\u017d\u2202\xf0 ,.'-]")], verbose_name='Apellido Materno*'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Asegurate de que el numero de telefono que proporcionas sea correcto.', regex='^\\+?1?\\d{9,15}$')], verbose_name='N\xfamero de Tel\xe9fono #2'),
        ),

    ]
