# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-02 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0010_auto_20190120_1743'),
    ]

    operations = [




        migrations.AlterField(
            model_name='employeefinancialdata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedata', to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeposition', to='HumanResources.Employee', verbose_name='Empleado'),
        ),
    ]
