# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0011_auto_20171108_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('percent_taxable', models.IntegerField(verbose_name='Porcentaje Grabable')),
                ('sat_key', models.CharField(max_length=30, verbose_name='Clave SAT')),
                ('law_type', models.CharField(max_length=30, verbose_name='Tipo de Ley')),
                ('status', models.CharField(max_length=1, verbose_name='Estatus')),
                ('accounting_account', models.IntegerField(verbose_name='Cuenta Contable')),
                ('comments', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningsDeductionsCategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Percepciones y Deducciones',
                'verbose_name_plural': 'Percepciones y Deducciones',
            },
        ),
        migrations.CreateModel(
            name='YNType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yn_type', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 24, 473248, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 24, 536562, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 24, 536613, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 24, 536653, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='earningsdeductions',
            name='taxable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.YNType', verbose_name='Grabable'),
        ),
        migrations.AddField(
            model_name='earningsdeductions',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningDeductionType', verbose_name='Tipo'),
        ),
    ]
