# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20181120_2028'),
        ('HumanResources', '0011_auto_20181120_1951'),
    ]

    operations = [

    ]
