# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 23:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20181120_2028'),
        ('HumanResources', '0012_payrollgroup_company'),
    ]

    operations = [

    ]
