# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 16:17
from __future__ import unicode_literals

import HumanResources.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0012_auto_20180420_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_key', models.CharField(max_length=64, unique=True, verbose_name='Clave del Contrato')),
                ('contract_type', models.CharField(choices=[('P', 'Permanente'), ('T', 'Temporal')], default='P', max_length=1, verbose_name='Tipo de Contrato')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Descripci\xf3n')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de T\xe9rmino')),
                ('contract_file', models.FileField(null=True, upload_to=HumanResources.models.upload_employee_contract, verbose_name='Contrato Escaneado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado')),
            ],
        ),
        migrations.AlterField(
            model_name='employeerequisition',
            name='vacancy_number',
            field=models.IntegerField(default=1, validators=set([django.core.validators.MinValueValidator(1)]), verbose_name='N\xfamero de Vacantes'),
        ),
    ]
