# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0012_auto_20190202_2212'),
    ]

    operations = [

        migrations.AddField(
            model_name='infonavitdata',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
            preserve_default=False,
        ),

    ]
