# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:31
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0012_auto_20171108_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEarningsDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningsDeductions', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Deducciones y Percepciones por Empleado',
                'verbose_name_plural': 'Deducciones y Percepciones por Empleado',
            },
        ),
        migrations.CreateModel(
            name='PayrollType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tipo de N\xf3mina')),
            ],
            options={
                'verbose_name': 'Tipos de N\xf3mina',
                'verbose_name_plural': 'Tipo de N\xf3mina',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 38, 477473, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 31, 38, 520545, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 38, 520624, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 31, 38, 520668, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='employeeearningsdeductions',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
    ]
