# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0013_auto_20181120_2351'),
    ]

    operations = [

    ]
