# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-20 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0013_auto_20180420_1617'),
        ('HumanResources', '0011_auto_20180420_1619'),
    ]

    operations = [
    ]
