# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0013_auto_20171108_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('month', models.CharField(max_length=30, verbose_name='Nombre')),
                ('year', models.CharField(max_length=30, verbose_name='Nombre')),
                ('week', models.CharField(max_length=30, verbose_name='Nombre')),
                ('start_period', models.CharField(max_length=30, verbose_name='Nombre')),
                ('end_period', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Periodos de N\xf3mina',
                'verbose_name_plural': 'Periodos de N\xf3mina',
            },
        ),
        migrations.CreateModel(
            name='PayrollToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('payroll_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollType', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'N\xf3mina a Procesar',
                'verbose_name_plural': 'N\xf3mina a Procesar',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 32, 12, 224065, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 32, 12, 250974, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 32, 12, 251026, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 32, 12, 251069, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
