# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0013_auto_20190202_2217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeloandetail',
            unique_together=set([('employeeloan', 'period')]),
        ),
    ]
