# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0014_auto_20171108_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProcessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PAYROLL_CLASIFICATION', verbose_name='Clasificaci\xf3n')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollPeriod', verbose_name='Periodo')),
                ('payroll_to_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollToProcess', verbose_name='N\xf3mina a Procesar')),
            ],
            options={
                'verbose_name': 'N\xf3mina Procesada',
                'verbose_name_plural': 'N\xf3mina Procesada',
            },
        ),
        migrations.CreateModel(
            name='PayrollProcessedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('taxed', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Grabable')),
                ('exempt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Excento')),
                ('earnings_deductions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EarningsDeductions', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Detalle de N\xf3mina Procesada',
                'verbose_name_plural': 'Detalle de N\xf3mina Procesada',
            },
        ),
        migrations.CreateModel(
            name='PayrollReceiptProcessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_days', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='D\xedas Trabajados')),
                ('total_perceptions', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total de Percepciones')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total de Deducciones')),
                ('total_payroll', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Neto')),
                ('taxed', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Grabado')),
                ('exempt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Excento')),
                ('daily_salry', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Salario Diario')),
                ('total_withholdings', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total de Deducciones')),
                ('total_discounts', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total de Descuentos')),
                ('stamp_version', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Versi\xf3n de Timbrado')),
                ('stamp_UUID', models.CharField(max_length=500, verbose_name='UUID de Timbrado')),
                ('stamp_date', models.DateTimeField(verbose_name='Fecha de Timbrado')),
                ('stamp_CFDI', models.CharField(max_length=500, verbose_name='CFDI Timbrado')),
                ('sat_certificate', models.CharField(max_length=500, verbose_name='Certificado del SAT')),
                ('stamp_sat', models.CharField(max_length=500, verbose_name='Timbrado del SAT')),
                ('stamp_xml', models.CharField(max_length=500, verbose_name='XML del Timbrado')),
                ('stamp_serie_id', models.CharField(max_length=500, verbose_name='Serie ID  de Timbrado')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
            ],
            options={
                'verbose_name': 'Recibo de N\xf3mina Procesada',
                'verbose_name_plural': 'Recibo de N\xf3mina Procesada',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 32, 29, 255195, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 21, 32, 29, 289278, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 32, 29, 289337, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 8, 21, 32, 29, 289443, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='payrollreceiptprocessed',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='payrollreceiptprocessed',
            name='payroll_processed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollProcessed', verbose_name='N\xf3mina Procesada'),
        ),
        migrations.AddField(
            model_name='payrollreceiptprocessed',
            name='printed_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.YNType', verbose_name='Recibo Impreso'),
        ),
        migrations.AddField(
            model_name='payrollprocesseddetail',
            name='payroll_receip_processed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollReceiptProcessed', verbose_name='Recibo de N\xf3mina Procesado'),
        ),
    ]
