# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0014_auto_20190207_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Empresa/Proyecto*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='subdirection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direction', chained_model_field='direction', default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n*'),
            preserve_default=False,
        ),
    ]
