# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0015_auto_20171108_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earningdeductiontype',
            options={'verbose_name': 'Tipos de Percepciones y Deducciones', 'verbose_name_plural': 'Tipo de Percepci\xf3n y Deducci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='earningsdeductionscategory',
            options={'verbose_name': 'Categorias de Percepciones y Deducciones', 'verbose_name_plural': 'Categoria de Percepci\xf3n y Deducci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='yntype',
            options={'verbose_name': 'SI/NO', 'verbose_name_plural': 'SI/NO'},
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='infonavitdata',
            name='employee',
        ),
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default='Bancomer', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infonavitdata',
            name='employee_financial_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EmployeeFinancialData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='earningdeductiontype',
            name='earning_deduction_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdeductionscategory',
            name='earnings_deductions_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, verbose_name='Expiraci\xf3n de Licencia para Conducir'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 38, 24, 194133, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 38, 24, 219766, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 20, 38, 24, 219815, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 20, 38, 24, 219850, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='payroll_clasification',
            name='payroll_classification',
            field=models.IntegerField(choices=[(1, 'Corporativa'), (2, 'Proyecto')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='yntype',
            name='yn_type',
            field=models.CharField(max_length=2),
        ),
    ]
