# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0015_auto_20181121_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Proyecto'),
        ),
    ]
