# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0015_auto_20190208_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='subdirection',
        ),
    ]
