# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-09 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0015_auto_20171108_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infonavitdata',
            name='employee',
        ),
        migrations.AddField(
            model_name='infonavitdata',
            name='employee_financial_data',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EmployeeFinancialData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 23, 8, 42, 857196, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 9, 23, 8, 42, 881074, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 9, 23, 8, 42, 881120, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 9, 23, 8, 42, 881167, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
