# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-12 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0016_auto_20190209_0357'),
    ]

    operations = [

    ]
