# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 20:18
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0016_auto_20171109_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Grupo de N\xf3mina',
                'verbose_name_plural': 'Grupo de N\xf3mina',
            },
        ),
        migrations.AlterField(
            model_name='earningsdeductions',
            name='category',
            field=models.CharField(choices=[('F', 'Fija'), ('V', 'Variable')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='earningsdeductions',
            name='taxable',
            field=models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='earningsdeductions',
            name='type',
            field=models.CharField(choices=[('D', 'Deducci\xf3n'), ('P', 'Percepci\xf3n')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, verbose_name='Expiraci\xf3n de Licencia para Conducir'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 18, 8, 707396, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 18, 8, 745439, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 20, 18, 8, 745503, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 20, 18, 8, 745581, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='CLABE',
            field=models.IntegerField(default=0, verbose_name='CLABE'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='account_number',
            field=models.IntegerField(default=0, verbose_name='N\xfamero de Cuenta'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='bank',
            field=models.CharField(choices=[('D', 'Deposito'), ('E', 'Efectivo'), ('T', 'Transferencia Interbancaria')], default='D', max_length=1, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='payment_method',
            field=models.CharField(choices=[('D', 'Deposito'), ('E', 'Efectivo'), ('T', 'Transferencia Interbancaria')], default='D', max_length=1, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='payroll_classification',
            field=models.CharField(choices=[('C', 'Corporativa'), ('P', 'Proyecto')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='end_period',
            field=models.DateField(verbose_name='Fin de Periodo'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, max_length=2, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='start_period',
            field=models.DateField(verbose_name='Inicio de Periodo'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(53), django.core.validators.MinValueValidator(1)], verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='year',
            field=models.IntegerField(default=2017, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(2017)], verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='payrollprocessed',
            name='payroll_classification',
            field=models.CharField(choices=[('C', 'Corporativa'), ('P', 'Proyecto')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='payrollreceiptprocessed',
            name='printed_receipt',
            field=models.CharField(choices=[('Y', 'Si'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='payrolltoprocess',
            name='payroll_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollType', verbose_name='Tipo de N\xf3mina'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='EarningDeductionType',
        ),
        migrations.DeleteModel(
            name='EarningsDeductionsCategory',
        ),
        migrations.DeleteModel(
            name='Payment_Method',
        ),
        migrations.DeleteModel(
            name='PAYROLL_CLASIFICATION',
        ),
        migrations.DeleteModel(
            name='YNType',
        ),
        migrations.AddField(
            model_name='employeepositiondescription',
            name='payroll_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollGroup', verbose_name='Grupo de N\xf3mina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='payroll_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollGroup', verbose_name='Grupo de N\xf3mina'),
            preserve_default=False,
        ),
    ]
