# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0017_auto_20171110_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningDeductionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_earnings_deductions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.EmployeeEarningsDeductions', verbose_name='Deducci\xf3n/Percepci\xf3n')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollPeriod', verbose_name='Periodo de N\xf3mina')),
            ],
            options={
                'verbose_name': 'Periodo Percepci\xf3n / Deducci\xf3n',
                'verbose_name_plural': 'Periodo Percepci\xf3n / Deducci\xf3n',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 22, 8, 3, 133592, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 22, 8, 3, 151180, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 22, 8, 3, 151207, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 22, 8, 3, 151243, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
    ]
