# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0018_auto_20171110_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_method',
            options={'verbose_name': 'Forma de Pago', 'verbose_name_plural': 'Formas de Pago'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='registry_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 50, 11, 488407, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 20, 50, 11, 504083, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 20, 50, 11, 504115, tzinfo=utc), verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='employeeassistance',
            name='exit_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 20, 50, 11, 504139, tzinfo=utc), verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='CLABE',
            field=models.CharField(default=0, max_length=20, verbose_name='CLABE'),
        ),
        migrations.AlterField(
            model_name='employeefinancialdata',
            name='account_number',
            field=models.CharField(default=0, max_length=20, verbose_name='N\xfamero de Cuenta'),
        ),
    ]
