# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20181120_2028'),
        ('HumanResources', '0018_auto_20181121_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollgroup',
            name='company',
        ),
        migrations.AddField(
            model_name='payrollgroup',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='payrollgroup',
            name='internal_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa'),
        ),
    ]
