# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0019_auto_20171110_2050'),
        ('HumanResources', '0017_auto_20171110_2018'),
    ]

    operations = [
    ]
