# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0019_auto_20181121_0341'),
    ]

    operations = [



    ]
