# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0020_auto_20181121_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='subdirection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection'),
        ),
        migrations.AddField(
            model_name='department',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area'),
        ),
        migrations.AddField(
            model_name='subdirection',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction'),
        ),
    ]
