# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0021_auto_20181122_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='subdirection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n'),
        ),
        migrations.AlterField(
            model_name='department',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subdirection', chained_model_field='subdirection', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='department',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subdirection', chained_model_field='subdirection', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Department', verbose_name='Departamento*'),
        ),
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='subdirection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direction', chained_model_field='direction', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='subdirection',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n'),
        ),
    ]
