# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 17:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0023_auto_20181122_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepositiondescription',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area'),
        ),
    ]
