# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0028_remove_direction_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='department',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='department',
            name='subdirection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n'),
        ),
    ]
