# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20181120_2028'),
        ('HumanResources', '0029_auto_20181122_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='internal_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa'),
        ),
    ]
