# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20181120_2028'),
        ('HumanResources', '0030_direction_internal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='internal_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa*'),
        ),
        migrations.AddField(
            model_name='department',
            name='internal_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa*'),
        ),
        migrations.AddField(
            model_name='subdirection',
            name='internal_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa*'),
        ),
        migrations.AlterField(
            model_name='area',
            name='direction',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='internal_company', chained_model_field='internal_company', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='area',
            name='subdirection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direction', chained_model_field='direction', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='department',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subdirection', chained_model_field='subdirection', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea*'),
        ),
        migrations.AlterField(
            model_name='department',
            name='direction',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='internal_company', chained_model_field='internal_company', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='department',
            name='subdirection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direction', chained_model_field='direction', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n*'),
        ),
        migrations.AlterField(
            model_name='subdirection',
            name='direction',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='internal_company', chained_model_field='internal_company', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n*'),
        ),
    ]
