# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0031_auto_20181122_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='area',
            name='internal_company',
        ),
        migrations.RemoveField(
            model_name='department',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='department',
            name='internal_company',
        ),
        migrations.RemoveField(
            model_name='department',
            name='subdirection',
        ),
        migrations.RemoveField(
            model_name='subdirection',
            name='internal_company',
        ),
        migrations.AlterField(
            model_name='area',
            name='subdirection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n'),
        ),
        migrations.AlterField(
            model_name='department',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea*'),
        ),
        migrations.AlterField(
            model_name='subdirection',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Direction', verbose_name='Direcci\xf3n*'),
        ),
    ]
