# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0032_auto_20181123_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\xc1rea'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='subdirection',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Subdirecci\xf3n'),
        ),
    ]
