# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0004_auto_20181123_1702'),
        ('HumanResources', '0033_auto_20181123_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\xc1rea'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='subdirection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Subdirecci\xf3n'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('subdirection', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('area', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together=set([('internal_company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='subdirection',
            unique_together=set([('direction', 'name')]),
        ),
    ]
