# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-27 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0034_auto_20181123_1702'),
    ]

    operations = [

        migrations.AlterField(
            model_name='jobprofile',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subdirection', chained_model_field='subdirection', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Area', verbose_name='\xc1rea*'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='department',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='area', chained_model_field='area', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Department', verbose_name='Departamento*'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='subdirection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direction', chained_model_field='direction', on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Subdirection', verbose_name='Subdirecci\xf3n*'),
        ),

    ]
