# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0036_auto_20181127_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'verbose_name_plural': 'Periodicidad',
            },
        ),
        migrations.AddField(
            model_name='employeefinancialdata',
            name='account_type',
            field=models.CharField(choices=[('P', 'Principal'), ('S', 'Secundaria')], default='P', max_length=1, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='periodicity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Periodicity', verbose_name='Periodicidad'),
            preserve_default=False,
        ),
    ]
