# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRecor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null='False', verbose_name='Fecha')),
                ('entry_registry', models.TimeField(blank=True, default=None, verbose_name='Hora de entrada')),
                ('exit_registry', models.TimeField(blank=True, default=None, verbose_name='Hora de salida')),
            ],
        ),
    ]
