# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssistanceRecor',
            new_name='AssistanceRecord',
        ),
    ]
