# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0007_auto_20171117_2209'),
        ('Assistance', '0002_auto_20171117_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistancerecord',
            options={'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.Employee', verbose_name='Empleado'),
            preserve_default=False,
        ),
    ]
