# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0008_auto_20171117_2210'),
        ('Assistance', '0003_auto_20171117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerecord',
            name='payroll_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HumanResources.PayrollPeriod', verbose_name='Periodo de n\xf3mina'),
            preserve_default=False,
        ),
    ]
