# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0005_assistancerecord_absence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistancerecord',
            old_name='date',
            new_name='record_date',
        ),
    ]
