# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0007_auto_20171119_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerecord',
            name='record_date',
            field=models.DateField(null='False', verbose_name='Fecha'),
        ),
    ]
