# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0008_auto_20171119_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerecord',
            name='entry_registry',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='assistancerecord',
            name='exit_registry',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de salida'),
        ),
    ]
