# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assistance', '0009_auto_20171120_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistancerecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='assistancerecord',
            name='payroll_period',
        ),
        migrations.DeleteModel(
            name='AssistanceRecord',
        ),
    ]
