# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Nombre de Usuario')),
                ('folio', models.CharField(max_length=36, unique=True, verbose_name='Folio')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'ordering': ['fecha'],
                'verbose_name': 'Registro de Carga',
                'verbose_name_plural': 'Registros de Carga',
            },
        ),
    ]
