# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='N\xfamero de Cuenta')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre de la Cuenta')),
                ('status', models.IntegerField(choices=[(1, 'Activa'), (2, 'Inactiva')], default=1, verbose_name='Estatus')),
                ('nature_account', models.IntegerField(choices=[(1, 'Deudora'), (2, 'Acreedora')], default=1, verbose_name='Naturaleza de Cuenta')),
                ('ledger_account', models.IntegerField(choices=[(1, 'Si'), (2, 'No')], default=1, verbose_name='Cuenta de Mayor')),
                ('level', models.CharField(max_length=500, verbose_name='Nivel')),
                ('item', models.CharField(max_length=500, verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='AccountingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True, verbose_name='Folio')),
                ('registry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('description', models.CharField(max_length=4096, verbose_name='Concepto')),
                ('reference', models.CharField(max_length=1024, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'P\xf3liza contable',
                'verbose_name_plural': 'P\xf3lizas Contables',
            },
        ),
        migrations.CreateModel(
            name='AccountingPolicyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096, verbose_name='Concepto')),
                ('debit', models.FloatField(default=0, verbose_name='Debe')),
                ('credit', models.FloatField(default=0, verbose_name='Haber')),
                ('registry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.Account', verbose_name='Cuenta')),
                ('accounting_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.AccountingPolicy', verbose_name='P\xf3liza')),
            ],
            options={
                'verbose_name': 'Detalle de P\xf3liza',
                'verbose_name_plural': 'Detalle de P\xf3lizas',
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_year', models.IntegerField(verbose_name='Ejercicio Contable')),
                ('account_period', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, verbose_name='Mes')),
                ('status', models.IntegerField(choices=[(1, 'Abierto'), (2, 'Cerrado'), (3, 'Auditado')], default=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'A\xf1o Contable',
                'verbose_name_plural': 'A\xf1o contable',
            },
        ),
        migrations.CreateModel(
            name='GroupingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5, verbose_name='Nivel')),
                ('grouping_code', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='C\xf3digo Agrupador')),
                ('account_name', models.CharField(max_length=500, verbose_name='Nombre de la Cuenta y/o subcuenta')),
            ],
            options={
                'verbose_name': 'C\xf3digo Agrupador de Cuentas del SAT.',
                'verbose_name_plural': 'C\xf3digo Agrupador de Cuentas del SAT.',
            },
        ),
        migrations.CreateModel(
            name='TypePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Tipo de P\xf3liza')),
                ('balanced_accounts', models.BooleanField(default=False, verbose_name='Cuadrar p\xf3liza')),
            ],
            options={
                'verbose_name': 'Tipo de P\xf3liza',
                'verbose_name_plural': 'Tipos de P\xf3liza',
            },
        ),
        migrations.AddField(
            model_name='accountingpolicy',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.FiscalPeriod', verbose_name='Periodo Fiscal'),
        ),
        migrations.AddField(
            model_name='accountingpolicy',
            name='type_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.TypePolicy', verbose_name='Tipo de P\xf3liza'),
        ),
        migrations.AddField(
            model_name='account',
            name='grouping_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.GroupingCode', verbose_name='C\xf3digo Agrupador SAT'),
        ),
        migrations.AddField(
            model_name='account',
            name='subsidiary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.Account', verbose_name='Subcuenta de'),
        ),
    ]
