# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialally',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel\xe9fono 2'),
        ),
    ]
