# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_bank_sat_bank'),
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAlly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('colony', models.CharField(max_length=255, verbose_name='Colonia')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('outdoor_number', models.CharField(max_length=10, verbose_name='No. Exterior')),
                ('indoor_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='No. Interior')),
                ('zip_code', models.CharField(max_length=5, verbose_name='C\xf3digo Postal')),
                ('rfc', models.CharField(max_length=20, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Tel\xe9fono')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('cellphone_number', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('office_number', models.CharField(blank=True, max_length=20, verbose_name='Tel\xe9fono de Oficina')),
                ('extension_number', models.CharField(blank=True, max_length=10, verbose_name='N\xfamero de Extensi\xf3n')),
                ('last_edit_date', models.DateTimeField(auto_now_add=True)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Nombre de la Persona')),
                ('bank_account', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Cuenta Bancaria')),
                ('employer_registration_number', models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='N\xfamero de Registro Patronal')),
                ('services', models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='Servicios que presta')),
                ('tax_person_type', models.CharField(choices=[('f', 'F\xedsica'), ('m', 'Moral')], default='m', max_length=1, verbose_name='Tipo de Persona')),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estatus')),
                ('type', models.IntegerField(choices=[('f', 'F\xedsica'), ('m', 'Moral')], default=0, verbose_name='Tipo')),
                ('accounting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.Account', verbose_name='Cuenta Contable')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Bank', verbose_name='Banco')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Pais', verbose_name='Pa\xeds')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='ERP.Estado', verbose_name='Estado')),
                ('town', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='ERP.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name_plural': 'Aliado Comercial',
            },
        ),
    ]
