# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '__first__'),
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True, verbose_name='Folio')),
                ('registry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('description', models.CharField(max_length=4096, verbose_name='Concepto')),
                ('reference', models.CharField(max_length=1024, verbose_name='Factura')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.FiscalPeriod', verbose_name='Periodo Fiscal')),
                ('internal_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa Interna')),
                ('type_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.TypePolicy', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gastos',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096, verbose_name='Concepto')),
                ('debit', models.FloatField(default=0, verbose_name='Monto')),
                ('deliveryto', models.CharField(max_length=100, verbose_name='Entregado a')),
                ('registry_date', models.DateField(verbose_name='Fecha de Registro')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.Expense', verbose_name='P\xf3liza')),
                ('internal_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa Interna')),
            ],
            options={
                'verbose_name': 'Detalle de Gasto',
                'verbose_name_plural': 'Detalle de Gastos',
            },
        ),
    ]
