# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 16:09
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_commercialally_phone_number_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialally',
            name='services',
            field=tinymce.models.HTMLField(blank=True, max_length=4096, null=True, verbose_name='Servicios que presta'),
        ),
    ]
