# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_expense_expensedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='folio',
        ),
        migrations.AddField(
            model_name='expense',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Monto'),
        ),
    ]
