# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20171214_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialally',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='groupingcode',
            name='level',
            field=models.IntegerField(null=True, verbose_name='Nivel'),
        ),
    ]
