# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20190404_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='fiscal_period',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='type_expense',
        ),
    ]
