# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20180223_1609'),
        ('Accounting', '0003_auto_20180226_2155'),
    ]

    operations = [
    ]
