# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCatalogs', '0003_auto_20180220_1810'),
        ('Accounting', '0004_auto_20171214_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='grouping_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subsidiary_account',
        ),
        migrations.AlterModelOptions(
            name='commercialally',
            options={'verbose_name': 'Aliado Comercial', 'verbose_name_plural': 'Aliado Comercial'},
        ),
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={'verbose_name': 'A\xf1o Contable', 'verbose_name_plural': 'A\xf1os contables'},
        ),
        migrations.AddField(
            model_name='accountingpolicy',
            name='internal_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa Interna'),
        ),
        migrations.AddField(
            model_name='commercialallycontact',
            name='commercialally',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounting.CommercialAlly', verbose_name='Aliado Comercial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountingpolicydetail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Account', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='accountingpolicydetail',
            name='registry_date',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='accounting_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Account', verbose_name='Cuenta Contable'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Nombre del Titular'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='services',
            field=models.TextField(blank=True, default='', max_length=4096, null=True, verbose_name='Servicios que presta'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='commercialally',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='commercialallycontact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='commercialallycontact',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='commercialallycontact',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.Municipio', verbose_name='Municipio'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='GroupingCode',
        ),
    ]
