# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_auto_20190404_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetail',
            name='registry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
    ]
