# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0007_auto_20190411_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounting.TypeDocument', verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
    ]
