# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0024_auto_20190404_0523'),
        ('Accounting', '0008_expense_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Project', verbose_name='Proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=4096, verbose_name='Descripci\xf3n'),
        ),
    ]
