# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-12 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_auto_20190411_1851'),
    ]

    operations = [

    ]
