# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0010_auto_20190412_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='internal_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SharedCatalogs.InternalCompany', verbose_name='Empresa Interna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Monto Liquido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_ammount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
