# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-12 15:28
from __future__ import unicode_literals

import Accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0012_auto_20190502_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file_evidence',
            field=models.FileField(default=0, upload_to=Accounting.models.upload_contract_file, verbose_name='Evidencias'),
            preserve_default=False,
        ),
    ]
